// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package GRPCService;

public final class Block {
  private Block() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BlockObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string reason = 2;</code>
     */
    java.lang.String getReason();
    /**
     * <code>string reason = 2;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code BlockObj}
   */
  public  static final class BlockObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BlockObj)
      BlockObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockObj.newBuilder() to construct.
    private BlockObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockObj() {
      username_ = "";
      reason_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.Block.internal_static_BlockObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.Block.internal_static_BlockObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.Block.BlockObj.class, GRPCService.Block.BlockObj.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FIELD_NUMBER = 2;
    private volatile java.lang.Object reason_;
    /**
     * <code>string reason = 2;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <code>string reason = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reason_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.Block.BlockObj)) {
        return super.equals(obj);
      }
      GRPCService.Block.BlockObj other = (GRPCService.Block.BlockObj) obj;

      boolean result = true;
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getReason()
          .equals(other.getReason());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.Block.BlockObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.BlockObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.BlockObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Block.BlockObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.Block.BlockObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Block.BlockObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.Block.BlockObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlockObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BlockObj)
        GRPCService.Block.BlockObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.Block.internal_static_BlockObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.Block.internal_static_BlockObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.Block.BlockObj.class, GRPCService.Block.BlockObj.Builder.class);
      }

      // Construct using GRPCService.Block.BlockObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        username_ = "";

        reason_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.Block.internal_static_BlockObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.Block.BlockObj getDefaultInstanceForType() {
        return GRPCService.Block.BlockObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.Block.BlockObj build() {
        GRPCService.Block.BlockObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.Block.BlockObj buildPartial() {
        GRPCService.Block.BlockObj result = new GRPCService.Block.BlockObj(this);
        result.username_ = username_;
        result.reason_ = reason_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.Block.BlockObj) {
          return mergeFrom((GRPCService.Block.BlockObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.Block.BlockObj other) {
        if (other == GRPCService.Block.BlockObj.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.Block.BlockObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.Block.BlockObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>string reason = 2;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reason = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reason = 2;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reason = 2;</code>
       */
      public Builder clearReason() {
        
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>string reason = 2;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BlockObj)
    }

    // @@protoc_insertion_point(class_scope:BlockObj)
    private static final GRPCService.Block.BlockObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.Block.BlockObj();
    }

    public static GRPCService.Block.BlockObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockObj>
        PARSER = new com.google.protobuf.AbstractParser<BlockObj>() {
      @java.lang.Override
      public BlockObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.Block.BlockObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListOfBlocksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListOfBlocks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    java.util.List<GRPCService.Block.BlockObj> 
        getAllBlocksList();
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    GRPCService.Block.BlockObj getAllBlocks(int index);
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    int getAllBlocksCount();
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    java.util.List<? extends GRPCService.Block.BlockObjOrBuilder> 
        getAllBlocksOrBuilderList();
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    GRPCService.Block.BlockObjOrBuilder getAllBlocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ListOfBlocks}
   */
  public  static final class ListOfBlocks extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ListOfBlocks)
      ListOfBlocksOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListOfBlocks.newBuilder() to construct.
    private ListOfBlocks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListOfBlocks() {
      allBlocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListOfBlocks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allBlocks_ = new java.util.ArrayList<GRPCService.Block.BlockObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              allBlocks_.add(
                  input.readMessage(GRPCService.Block.BlockObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allBlocks_ = java.util.Collections.unmodifiableList(allBlocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.Block.internal_static_ListOfBlocks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.Block.internal_static_ListOfBlocks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.Block.ListOfBlocks.class, GRPCService.Block.ListOfBlocks.Builder.class);
    }

    public static final int ALLBLOCKS_FIELD_NUMBER = 1;
    private java.util.List<GRPCService.Block.BlockObj> allBlocks_;
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    public java.util.List<GRPCService.Block.BlockObj> getAllBlocksList() {
      return allBlocks_;
    }
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    public java.util.List<? extends GRPCService.Block.BlockObjOrBuilder> 
        getAllBlocksOrBuilderList() {
      return allBlocks_;
    }
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    public int getAllBlocksCount() {
      return allBlocks_.size();
    }
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    public GRPCService.Block.BlockObj getAllBlocks(int index) {
      return allBlocks_.get(index);
    }
    /**
     * <code>repeated .BlockObj allBlocks = 1;</code>
     */
    public GRPCService.Block.BlockObjOrBuilder getAllBlocksOrBuilder(
        int index) {
      return allBlocks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allBlocks_.size(); i++) {
        output.writeMessage(1, allBlocks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allBlocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allBlocks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.Block.ListOfBlocks)) {
        return super.equals(obj);
      }
      GRPCService.Block.ListOfBlocks other = (GRPCService.Block.ListOfBlocks) obj;

      boolean result = true;
      result = result && getAllBlocksList()
          .equals(other.getAllBlocksList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAllBlocksCount() > 0) {
        hash = (37 * hash) + ALLBLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getAllBlocksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.Block.ListOfBlocks parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Block.ListOfBlocks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.Block.ListOfBlocks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Block.ListOfBlocks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.Block.ListOfBlocks prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListOfBlocks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListOfBlocks)
        GRPCService.Block.ListOfBlocksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.Block.internal_static_ListOfBlocks_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.Block.internal_static_ListOfBlocks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.Block.ListOfBlocks.class, GRPCService.Block.ListOfBlocks.Builder.class);
      }

      // Construct using GRPCService.Block.ListOfBlocks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllBlocksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (allBlocksBuilder_ == null) {
          allBlocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allBlocksBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.Block.internal_static_ListOfBlocks_descriptor;
      }

      @java.lang.Override
      public GRPCService.Block.ListOfBlocks getDefaultInstanceForType() {
        return GRPCService.Block.ListOfBlocks.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.Block.ListOfBlocks build() {
        GRPCService.Block.ListOfBlocks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.Block.ListOfBlocks buildPartial() {
        GRPCService.Block.ListOfBlocks result = new GRPCService.Block.ListOfBlocks(this);
        int from_bitField0_ = bitField0_;
        if (allBlocksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allBlocks_ = java.util.Collections.unmodifiableList(allBlocks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allBlocks_ = allBlocks_;
        } else {
          result.allBlocks_ = allBlocksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.Block.ListOfBlocks) {
          return mergeFrom((GRPCService.Block.ListOfBlocks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.Block.ListOfBlocks other) {
        if (other == GRPCService.Block.ListOfBlocks.getDefaultInstance()) return this;
        if (allBlocksBuilder_ == null) {
          if (!other.allBlocks_.isEmpty()) {
            if (allBlocks_.isEmpty()) {
              allBlocks_ = other.allBlocks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllBlocksIsMutable();
              allBlocks_.addAll(other.allBlocks_);
            }
            onChanged();
          }
        } else {
          if (!other.allBlocks_.isEmpty()) {
            if (allBlocksBuilder_.isEmpty()) {
              allBlocksBuilder_.dispose();
              allBlocksBuilder_ = null;
              allBlocks_ = other.allBlocks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allBlocksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllBlocksFieldBuilder() : null;
            } else {
              allBlocksBuilder_.addAllMessages(other.allBlocks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.Block.ListOfBlocks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.Block.ListOfBlocks) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GRPCService.Block.BlockObj> allBlocks_ =
        java.util.Collections.emptyList();
      private void ensureAllBlocksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allBlocks_ = new java.util.ArrayList<GRPCService.Block.BlockObj>(allBlocks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.Block.BlockObj, GRPCService.Block.BlockObj.Builder, GRPCService.Block.BlockObjOrBuilder> allBlocksBuilder_;

      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public java.util.List<GRPCService.Block.BlockObj> getAllBlocksList() {
        if (allBlocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allBlocks_);
        } else {
          return allBlocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public int getAllBlocksCount() {
        if (allBlocksBuilder_ == null) {
          return allBlocks_.size();
        } else {
          return allBlocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public GRPCService.Block.BlockObj getAllBlocks(int index) {
        if (allBlocksBuilder_ == null) {
          return allBlocks_.get(index);
        } else {
          return allBlocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder setAllBlocks(
          int index, GRPCService.Block.BlockObj value) {
        if (allBlocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBlocksIsMutable();
          allBlocks_.set(index, value);
          onChanged();
        } else {
          allBlocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder setAllBlocks(
          int index, GRPCService.Block.BlockObj.Builder builderForValue) {
        if (allBlocksBuilder_ == null) {
          ensureAllBlocksIsMutable();
          allBlocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          allBlocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder addAllBlocks(GRPCService.Block.BlockObj value) {
        if (allBlocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBlocksIsMutable();
          allBlocks_.add(value);
          onChanged();
        } else {
          allBlocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder addAllBlocks(
          int index, GRPCService.Block.BlockObj value) {
        if (allBlocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBlocksIsMutable();
          allBlocks_.add(index, value);
          onChanged();
        } else {
          allBlocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder addAllBlocks(
          GRPCService.Block.BlockObj.Builder builderForValue) {
        if (allBlocksBuilder_ == null) {
          ensureAllBlocksIsMutable();
          allBlocks_.add(builderForValue.build());
          onChanged();
        } else {
          allBlocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder addAllBlocks(
          int index, GRPCService.Block.BlockObj.Builder builderForValue) {
        if (allBlocksBuilder_ == null) {
          ensureAllBlocksIsMutable();
          allBlocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          allBlocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder addAllAllBlocks(
          java.lang.Iterable<? extends GRPCService.Block.BlockObj> values) {
        if (allBlocksBuilder_ == null) {
          ensureAllBlocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allBlocks_);
          onChanged();
        } else {
          allBlocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder clearAllBlocks() {
        if (allBlocksBuilder_ == null) {
          allBlocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allBlocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public Builder removeAllBlocks(int index) {
        if (allBlocksBuilder_ == null) {
          ensureAllBlocksIsMutable();
          allBlocks_.remove(index);
          onChanged();
        } else {
          allBlocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public GRPCService.Block.BlockObj.Builder getAllBlocksBuilder(
          int index) {
        return getAllBlocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public GRPCService.Block.BlockObjOrBuilder getAllBlocksOrBuilder(
          int index) {
        if (allBlocksBuilder_ == null) {
          return allBlocks_.get(index);  } else {
          return allBlocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public java.util.List<? extends GRPCService.Block.BlockObjOrBuilder> 
           getAllBlocksOrBuilderList() {
        if (allBlocksBuilder_ != null) {
          return allBlocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allBlocks_);
        }
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public GRPCService.Block.BlockObj.Builder addAllBlocksBuilder() {
        return getAllBlocksFieldBuilder().addBuilder(
            GRPCService.Block.BlockObj.getDefaultInstance());
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public GRPCService.Block.BlockObj.Builder addAllBlocksBuilder(
          int index) {
        return getAllBlocksFieldBuilder().addBuilder(
            index, GRPCService.Block.BlockObj.getDefaultInstance());
      }
      /**
       * <code>repeated .BlockObj allBlocks = 1;</code>
       */
      public java.util.List<GRPCService.Block.BlockObj.Builder> 
           getAllBlocksBuilderList() {
        return getAllBlocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.Block.BlockObj, GRPCService.Block.BlockObj.Builder, GRPCService.Block.BlockObjOrBuilder> 
          getAllBlocksFieldBuilder() {
        if (allBlocksBuilder_ == null) {
          allBlocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPCService.Block.BlockObj, GRPCService.Block.BlockObj.Builder, GRPCService.Block.BlockObjOrBuilder>(
                  allBlocks_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allBlocks_ = null;
        }
        return allBlocksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ListOfBlocks)
    }

    // @@protoc_insertion_point(class_scope:ListOfBlocks)
    private static final GRPCService.Block.ListOfBlocks DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.Block.ListOfBlocks();
    }

    public static GRPCService.Block.ListOfBlocks getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListOfBlocks>
        PARSER = new com.google.protobuf.AbstractParser<ListOfBlocks>() {
      @java.lang.Override
      public ListOfBlocks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListOfBlocks(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListOfBlocks> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListOfBlocks> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.Block.ListOfBlocks getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EmptyBlock)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code EmptyBlock}
   */
  public  static final class EmptyBlock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EmptyBlock)
      EmptyBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmptyBlock.newBuilder() to construct.
    private EmptyBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmptyBlock() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmptyBlock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.Block.internal_static_EmptyBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.Block.internal_static_EmptyBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.Block.EmptyBlock.class, GRPCService.Block.EmptyBlock.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.Block.EmptyBlock)) {
        return super.equals(obj);
      }
      GRPCService.Block.EmptyBlock other = (GRPCService.Block.EmptyBlock) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.Block.EmptyBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Block.EmptyBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.Block.EmptyBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Block.EmptyBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.Block.EmptyBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EmptyBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EmptyBlock)
        GRPCService.Block.EmptyBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.Block.internal_static_EmptyBlock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.Block.internal_static_EmptyBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.Block.EmptyBlock.class, GRPCService.Block.EmptyBlock.Builder.class);
      }

      // Construct using GRPCService.Block.EmptyBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.Block.internal_static_EmptyBlock_descriptor;
      }

      @java.lang.Override
      public GRPCService.Block.EmptyBlock getDefaultInstanceForType() {
        return GRPCService.Block.EmptyBlock.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.Block.EmptyBlock build() {
        GRPCService.Block.EmptyBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.Block.EmptyBlock buildPartial() {
        GRPCService.Block.EmptyBlock result = new GRPCService.Block.EmptyBlock(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.Block.EmptyBlock) {
          return mergeFrom((GRPCService.Block.EmptyBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.Block.EmptyBlock other) {
        if (other == GRPCService.Block.EmptyBlock.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.Block.EmptyBlock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.Block.EmptyBlock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EmptyBlock)
    }

    // @@protoc_insertion_point(class_scope:EmptyBlock)
    private static final GRPCService.Block.EmptyBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.Block.EmptyBlock();
    }

    public static GRPCService.Block.EmptyBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyBlock>
        PARSER = new com.google.protobuf.AbstractParser<EmptyBlock>() {
      @java.lang.Override
      public EmptyBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmptyBlock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmptyBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyBlock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.Block.EmptyBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlockObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlockObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListOfBlocks_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListOfBlocks_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyBlock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Block.proto\032\nuser.proto\",\n\010BlockObj\022\020\n" +
      "\010username\030\001 \001(\t\022\016\n\006reason\030\002 \001(\t\",\n\014ListO" +
      "fBlocks\022\034\n\tallBlocks\030\001 \003(\0132\t.BlockObj\"\014\n" +
      "\nEmptyBlock2\223\001\n\nBlockProto\022%\n\tBlockUser\022" +
      "\t.BlockObj\032\r.user.UserObj\022,\n\013UnBlockUser" +
      "\022\016.user.Username\032\r.user.UserObj\0220\n\022getAl" +
      "lBlockedUsers\022\013.EmptyBlock\032\r.ListOfBlock" +
      "sB\r\n\013GRPCServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_BlockObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BlockObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlockObj_descriptor,
        new java.lang.String[] { "Username", "Reason", });
    internal_static_ListOfBlocks_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ListOfBlocks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListOfBlocks_descriptor,
        new java.lang.String[] { "AllBlocks", });
    internal_static_EmptyBlock_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EmptyBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyBlock_descriptor,
        new java.lang.String[] { });
    GRPCService.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
