// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package GRPCService;

public final class ReportOuterClass {
  private ReportOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyReportMarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.EmptyReportMark)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Report.EmptyReportMark}
   */
  public  static final class EmptyReportMark extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.EmptyReportMark)
      EmptyReportMarkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmptyReportMark.newBuilder() to construct.
    private EmptyReportMark(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmptyReportMark() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmptyReportMark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.ReportOuterClass.internal_static_Report_EmptyReportMark_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.ReportOuterClass.internal_static_Report_EmptyReportMark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.ReportOuterClass.EmptyReportMark.class, GRPCService.ReportOuterClass.EmptyReportMark.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.ReportOuterClass.EmptyReportMark)) {
        return super.equals(obj);
      }
      GRPCService.ReportOuterClass.EmptyReportMark other = (GRPCService.ReportOuterClass.EmptyReportMark) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.EmptyReportMark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.ReportOuterClass.EmptyReportMark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.EmptyReportMark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.EmptyReportMark)
        GRPCService.ReportOuterClass.EmptyReportMarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.ReportOuterClass.internal_static_Report_EmptyReportMark_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.ReportOuterClass.internal_static_Report_EmptyReportMark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.ReportOuterClass.EmptyReportMark.class, GRPCService.ReportOuterClass.EmptyReportMark.Builder.class);
      }

      // Construct using GRPCService.ReportOuterClass.EmptyReportMark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.ReportOuterClass.internal_static_Report_EmptyReportMark_descriptor;
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.EmptyReportMark getDefaultInstanceForType() {
        return GRPCService.ReportOuterClass.EmptyReportMark.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.EmptyReportMark build() {
        GRPCService.ReportOuterClass.EmptyReportMark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.EmptyReportMark buildPartial() {
        GRPCService.ReportOuterClass.EmptyReportMark result = new GRPCService.ReportOuterClass.EmptyReportMark(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.ReportOuterClass.EmptyReportMark) {
          return mergeFrom((GRPCService.ReportOuterClass.EmptyReportMark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.ReportOuterClass.EmptyReportMark other) {
        if (other == GRPCService.ReportOuterClass.EmptyReportMark.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.ReportOuterClass.EmptyReportMark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.ReportOuterClass.EmptyReportMark) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Report.EmptyReportMark)
    }

    // @@protoc_insertion_point(class_scope:Report.EmptyReportMark)
    private static final GRPCService.ReportOuterClass.EmptyReportMark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.ReportOuterClass.EmptyReportMark();
    }

    public static GRPCService.ReportOuterClass.EmptyReportMark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyReportMark>
        PARSER = new com.google.protobuf.AbstractParser<EmptyReportMark>() {
      @java.lang.Override
      public EmptyReportMark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmptyReportMark(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmptyReportMark> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyReportMark> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.ReportOuterClass.EmptyReportMark getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListOfReportsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.ListOfReports)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    java.util.List<GRPCService.ReportOuterClass.ReportObj> 
        getReportObjList();
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    GRPCService.ReportOuterClass.ReportObj getReportObj(int index);
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    int getReportObjCount();
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    java.util.List<? extends GRPCService.ReportOuterClass.ReportObjOrBuilder> 
        getReportObjOrBuilderList();
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    GRPCService.ReportOuterClass.ReportObjOrBuilder getReportObjOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Report.ListOfReports}
   */
  public  static final class ListOfReports extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.ListOfReports)
      ListOfReportsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListOfReports.newBuilder() to construct.
    private ListOfReports(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListOfReports() {
      reportObj_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListOfReports(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                reportObj_ = new java.util.ArrayList<GRPCService.ReportOuterClass.ReportObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              reportObj_.add(
                  input.readMessage(GRPCService.ReportOuterClass.ReportObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          reportObj_ = java.util.Collections.unmodifiableList(reportObj_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.ReportOuterClass.internal_static_Report_ListOfReports_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.ReportOuterClass.internal_static_Report_ListOfReports_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.ReportOuterClass.ListOfReports.class, GRPCService.ReportOuterClass.ListOfReports.Builder.class);
    }

    public static final int REPORTOBJ_FIELD_NUMBER = 1;
    private java.util.List<GRPCService.ReportOuterClass.ReportObj> reportObj_;
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    public java.util.List<GRPCService.ReportOuterClass.ReportObj> getReportObjList() {
      return reportObj_;
    }
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    public java.util.List<? extends GRPCService.ReportOuterClass.ReportObjOrBuilder> 
        getReportObjOrBuilderList() {
      return reportObj_;
    }
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    public int getReportObjCount() {
      return reportObj_.size();
    }
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    public GRPCService.ReportOuterClass.ReportObj getReportObj(int index) {
      return reportObj_.get(index);
    }
    /**
     * <code>repeated .Report.ReportObj reportObj = 1;</code>
     */
    public GRPCService.ReportOuterClass.ReportObjOrBuilder getReportObjOrBuilder(
        int index) {
      return reportObj_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < reportObj_.size(); i++) {
        output.writeMessage(1, reportObj_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reportObj_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reportObj_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.ReportOuterClass.ListOfReports)) {
        return super.equals(obj);
      }
      GRPCService.ReportOuterClass.ListOfReports other = (GRPCService.ReportOuterClass.ListOfReports) obj;

      boolean result = true;
      result = result && getReportObjList()
          .equals(other.getReportObjList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getReportObjCount() > 0) {
        hash = (37 * hash) + REPORTOBJ_FIELD_NUMBER;
        hash = (53 * hash) + getReportObjList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.ListOfReports parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.ReportOuterClass.ListOfReports prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.ListOfReports}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.ListOfReports)
        GRPCService.ReportOuterClass.ListOfReportsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.ReportOuterClass.internal_static_Report_ListOfReports_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.ReportOuterClass.internal_static_Report_ListOfReports_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.ReportOuterClass.ListOfReports.class, GRPCService.ReportOuterClass.ListOfReports.Builder.class);
      }

      // Construct using GRPCService.ReportOuterClass.ListOfReports.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReportObjFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (reportObjBuilder_ == null) {
          reportObj_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reportObjBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.ReportOuterClass.internal_static_Report_ListOfReports_descriptor;
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.ListOfReports getDefaultInstanceForType() {
        return GRPCService.ReportOuterClass.ListOfReports.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.ListOfReports build() {
        GRPCService.ReportOuterClass.ListOfReports result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.ListOfReports buildPartial() {
        GRPCService.ReportOuterClass.ListOfReports result = new GRPCService.ReportOuterClass.ListOfReports(this);
        int from_bitField0_ = bitField0_;
        if (reportObjBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            reportObj_ = java.util.Collections.unmodifiableList(reportObj_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reportObj_ = reportObj_;
        } else {
          result.reportObj_ = reportObjBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.ReportOuterClass.ListOfReports) {
          return mergeFrom((GRPCService.ReportOuterClass.ListOfReports)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.ReportOuterClass.ListOfReports other) {
        if (other == GRPCService.ReportOuterClass.ListOfReports.getDefaultInstance()) return this;
        if (reportObjBuilder_ == null) {
          if (!other.reportObj_.isEmpty()) {
            if (reportObj_.isEmpty()) {
              reportObj_ = other.reportObj_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReportObjIsMutable();
              reportObj_.addAll(other.reportObj_);
            }
            onChanged();
          }
        } else {
          if (!other.reportObj_.isEmpty()) {
            if (reportObjBuilder_.isEmpty()) {
              reportObjBuilder_.dispose();
              reportObjBuilder_ = null;
              reportObj_ = other.reportObj_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reportObjBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReportObjFieldBuilder() : null;
            } else {
              reportObjBuilder_.addAllMessages(other.reportObj_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.ReportOuterClass.ListOfReports parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.ReportOuterClass.ListOfReports) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GRPCService.ReportOuterClass.ReportObj> reportObj_ =
        java.util.Collections.emptyList();
      private void ensureReportObjIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reportObj_ = new java.util.ArrayList<GRPCService.ReportOuterClass.ReportObj>(reportObj_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.ReportOuterClass.ReportObj, GRPCService.ReportOuterClass.ReportObj.Builder, GRPCService.ReportOuterClass.ReportObjOrBuilder> reportObjBuilder_;

      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public java.util.List<GRPCService.ReportOuterClass.ReportObj> getReportObjList() {
        if (reportObjBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reportObj_);
        } else {
          return reportObjBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public int getReportObjCount() {
        if (reportObjBuilder_ == null) {
          return reportObj_.size();
        } else {
          return reportObjBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public GRPCService.ReportOuterClass.ReportObj getReportObj(int index) {
        if (reportObjBuilder_ == null) {
          return reportObj_.get(index);
        } else {
          return reportObjBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder setReportObj(
          int index, GRPCService.ReportOuterClass.ReportObj value) {
        if (reportObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportObjIsMutable();
          reportObj_.set(index, value);
          onChanged();
        } else {
          reportObjBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder setReportObj(
          int index, GRPCService.ReportOuterClass.ReportObj.Builder builderForValue) {
        if (reportObjBuilder_ == null) {
          ensureReportObjIsMutable();
          reportObj_.set(index, builderForValue.build());
          onChanged();
        } else {
          reportObjBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder addReportObj(GRPCService.ReportOuterClass.ReportObj value) {
        if (reportObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportObjIsMutable();
          reportObj_.add(value);
          onChanged();
        } else {
          reportObjBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder addReportObj(
          int index, GRPCService.ReportOuterClass.ReportObj value) {
        if (reportObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportObjIsMutable();
          reportObj_.add(index, value);
          onChanged();
        } else {
          reportObjBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder addReportObj(
          GRPCService.ReportOuterClass.ReportObj.Builder builderForValue) {
        if (reportObjBuilder_ == null) {
          ensureReportObjIsMutable();
          reportObj_.add(builderForValue.build());
          onChanged();
        } else {
          reportObjBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder addReportObj(
          int index, GRPCService.ReportOuterClass.ReportObj.Builder builderForValue) {
        if (reportObjBuilder_ == null) {
          ensureReportObjIsMutable();
          reportObj_.add(index, builderForValue.build());
          onChanged();
        } else {
          reportObjBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder addAllReportObj(
          java.lang.Iterable<? extends GRPCService.ReportOuterClass.ReportObj> values) {
        if (reportObjBuilder_ == null) {
          ensureReportObjIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reportObj_);
          onChanged();
        } else {
          reportObjBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder clearReportObj() {
        if (reportObjBuilder_ == null) {
          reportObj_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reportObjBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public Builder removeReportObj(int index) {
        if (reportObjBuilder_ == null) {
          ensureReportObjIsMutable();
          reportObj_.remove(index);
          onChanged();
        } else {
          reportObjBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public GRPCService.ReportOuterClass.ReportObj.Builder getReportObjBuilder(
          int index) {
        return getReportObjFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public GRPCService.ReportOuterClass.ReportObjOrBuilder getReportObjOrBuilder(
          int index) {
        if (reportObjBuilder_ == null) {
          return reportObj_.get(index);  } else {
          return reportObjBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public java.util.List<? extends GRPCService.ReportOuterClass.ReportObjOrBuilder> 
           getReportObjOrBuilderList() {
        if (reportObjBuilder_ != null) {
          return reportObjBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reportObj_);
        }
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public GRPCService.ReportOuterClass.ReportObj.Builder addReportObjBuilder() {
        return getReportObjFieldBuilder().addBuilder(
            GRPCService.ReportOuterClass.ReportObj.getDefaultInstance());
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public GRPCService.ReportOuterClass.ReportObj.Builder addReportObjBuilder(
          int index) {
        return getReportObjFieldBuilder().addBuilder(
            index, GRPCService.ReportOuterClass.ReportObj.getDefaultInstance());
      }
      /**
       * <code>repeated .Report.ReportObj reportObj = 1;</code>
       */
      public java.util.List<GRPCService.ReportOuterClass.ReportObj.Builder> 
           getReportObjBuilderList() {
        return getReportObjFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.ReportOuterClass.ReportObj, GRPCService.ReportOuterClass.ReportObj.Builder, GRPCService.ReportOuterClass.ReportObjOrBuilder> 
          getReportObjFieldBuilder() {
        if (reportObjBuilder_ == null) {
          reportObjBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPCService.ReportOuterClass.ReportObj, GRPCService.ReportOuterClass.ReportObj.Builder, GRPCService.ReportOuterClass.ReportObjOrBuilder>(
                  reportObj_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          reportObj_ = null;
        }
        return reportObjBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Report.ListOfReports)
    }

    // @@protoc_insertion_point(class_scope:Report.ListOfReports)
    private static final GRPCService.ReportOuterClass.ListOfReports DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.ReportOuterClass.ListOfReports();
    }

    public static GRPCService.ReportOuterClass.ListOfReports getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListOfReports>
        PARSER = new com.google.protobuf.AbstractParser<ListOfReports>() {
      @java.lang.Override
      public ListOfReports parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListOfReports(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListOfReports> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListOfReports> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.ReportOuterClass.ListOfReports getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReportObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.ReportObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 postId = 1;</code>
     */
    int getPostId();

    /**
     * <code>string reporterUsername = 2;</code>
     */
    java.lang.String getReporterUsername();
    /**
     * <code>string reporterUsername = 2;</code>
     */
    com.google.protobuf.ByteString
        getReporterUsernameBytes();

    /**
     * <code>string reason = 3;</code>
     */
    java.lang.String getReason();
    /**
     * <code>string reason = 3;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code Report.ReportObj}
   */
  public  static final class ReportObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.ReportObj)
      ReportObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportObj.newBuilder() to construct.
    private ReportObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportObj() {
      postId_ = 0;
      reporterUsername_ = "";
      reason_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReportObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              postId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              reporterUsername_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.ReportOuterClass.internal_static_Report_ReportObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.ReportOuterClass.internal_static_Report_ReportObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.ReportOuterClass.ReportObj.class, GRPCService.ReportOuterClass.ReportObj.Builder.class);
    }

    public static final int POSTID_FIELD_NUMBER = 1;
    private int postId_;
    /**
     * <code>int32 postId = 1;</code>
     */
    public int getPostId() {
      return postId_;
    }

    public static final int REPORTERUSERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object reporterUsername_;
    /**
     * <code>string reporterUsername = 2;</code>
     */
    public java.lang.String getReporterUsername() {
      java.lang.Object ref = reporterUsername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reporterUsername_ = s;
        return s;
      }
    }
    /**
     * <code>string reporterUsername = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReporterUsernameBytes() {
      java.lang.Object ref = reporterUsername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reporterUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FIELD_NUMBER = 3;
    private volatile java.lang.Object reason_;
    /**
     * <code>string reason = 3;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <code>string reason = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (postId_ != 0) {
        output.writeInt32(1, postId_);
      }
      if (!getReporterUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reporterUsername_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reason_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, postId_);
      }
      if (!getReporterUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reporterUsername_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.ReportOuterClass.ReportObj)) {
        return super.equals(obj);
      }
      GRPCService.ReportOuterClass.ReportObj other = (GRPCService.ReportOuterClass.ReportObj) obj;

      boolean result = true;
      result = result && (getPostId()
          == other.getPostId());
      result = result && getReporterUsername()
          .equals(other.getReporterUsername());
      result = result && getReason()
          .equals(other.getReason());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + getPostId();
      hash = (37 * hash) + REPORTERUSERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReporterUsername().hashCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.ReportOuterClass.ReportObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.ReportOuterClass.ReportObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.ReportObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.ReportObj)
        GRPCService.ReportOuterClass.ReportObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.ReportOuterClass.internal_static_Report_ReportObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.ReportOuterClass.internal_static_Report_ReportObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.ReportOuterClass.ReportObj.class, GRPCService.ReportOuterClass.ReportObj.Builder.class);
      }

      // Construct using GRPCService.ReportOuterClass.ReportObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        postId_ = 0;

        reporterUsername_ = "";

        reason_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.ReportOuterClass.internal_static_Report_ReportObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.ReportObj getDefaultInstanceForType() {
        return GRPCService.ReportOuterClass.ReportObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.ReportObj build() {
        GRPCService.ReportOuterClass.ReportObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.ReportOuterClass.ReportObj buildPartial() {
        GRPCService.ReportOuterClass.ReportObj result = new GRPCService.ReportOuterClass.ReportObj(this);
        result.postId_ = postId_;
        result.reporterUsername_ = reporterUsername_;
        result.reason_ = reason_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.ReportOuterClass.ReportObj) {
          return mergeFrom((GRPCService.ReportOuterClass.ReportObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.ReportOuterClass.ReportObj other) {
        if (other == GRPCService.ReportOuterClass.ReportObj.getDefaultInstance()) return this;
        if (other.getPostId() != 0) {
          setPostId(other.getPostId());
        }
        if (!other.getReporterUsername().isEmpty()) {
          reporterUsername_ = other.reporterUsername_;
          onChanged();
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.ReportOuterClass.ReportObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.ReportOuterClass.ReportObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int postId_ ;
      /**
       * <code>int32 postId = 1;</code>
       */
      public int getPostId() {
        return postId_;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder setPostId(int value) {
        
        postId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder clearPostId() {
        
        postId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reporterUsername_ = "";
      /**
       * <code>string reporterUsername = 2;</code>
       */
      public java.lang.String getReporterUsername() {
        java.lang.Object ref = reporterUsername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reporterUsername_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reporterUsername = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReporterUsernameBytes() {
        java.lang.Object ref = reporterUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reporterUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reporterUsername = 2;</code>
       */
      public Builder setReporterUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reporterUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reporterUsername = 2;</code>
       */
      public Builder clearReporterUsername() {
        
        reporterUsername_ = getDefaultInstance().getReporterUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string reporterUsername = 2;</code>
       */
      public Builder setReporterUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reporterUsername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>string reason = 3;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reason = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reason = 3;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reason = 3;</code>
       */
      public Builder clearReason() {
        
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>string reason = 3;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Report.ReportObj)
    }

    // @@protoc_insertion_point(class_scope:Report.ReportObj)
    private static final GRPCService.ReportOuterClass.ReportObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.ReportOuterClass.ReportObj();
    }

    public static GRPCService.ReportOuterClass.ReportObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportObj>
        PARSER = new com.google.protobuf.AbstractParser<ReportObj>() {
      @java.lang.Override
      public ReportObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReportObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.ReportOuterClass.ReportObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_EmptyReportMark_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_EmptyReportMark_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_ListOfReports_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_ListOfReports_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_ReportObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_ReportObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014report.proto\022\006Report\032\npost.proto\032\nuser" +
      ".proto\"\021\n\017EmptyReportMark\"5\n\rListOfRepor" +
      "ts\022$\n\treportObj\030\001 \003(\0132\021.Report.ReportObj" +
      "\"E\n\tReportObj\022\016\n\006postId\030\001 \001(\005\022\030\n\020reporte" +
      "rUsername\030\002 \001(\t\022\016\n\006reason\030\003 \001(\t2\202\001\n\006Repo" +
      "rt\022:\n\014RemoveReport\022\021.Report.ReportObj\032\027." +
      "Report.EmptyReportMark\022<\n\nGetReports\022\027.R" +
      "eport.EmptyReportMark\032\025.Report.ListOfRep" +
      "ortsB\r\n\013GRPCServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.PostOuterClass.getDescriptor(),
          GRPCService.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Report_EmptyReportMark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Report_EmptyReportMark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_EmptyReportMark_descriptor,
        new java.lang.String[] { });
    internal_static_Report_ListOfReports_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Report_ListOfReports_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_ListOfReports_descriptor,
        new java.lang.String[] { "ReportObj", });
    internal_static_Report_ReportObj_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Report_ReportObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_ReportObj_descriptor,
        new java.lang.String[] { "PostId", "ReporterUsername", "Reason", });
    GRPCService.PostOuterClass.getDescriptor();
    GRPCService.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
